// import { Component } from "react";

/* eslint-disable linebreak-style */
export const USER_UI_START_LOADING = 'USER_UI_START_LOADING';
export const USER_UI_STOP_LOADING = 'USER_UI_STOP_LOADING';

export const SET_USER = 'SET_USER';
export const FETCH_USER_DATA_REQUEST = 'FETCH_USER_DATA_REQUEST';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';
export const RESET_USER_DATA = 'RESET_USER_DATA';

export const FETCH_COMMUNITY_DATA_REQUEST = 'FETCH_COMMUNITY_DATA_REQUEST';
export const FETCH_COMMUNITY_DATA_SUCCESS = 'FETCH_COMMUNITY_DATA_SUCCESS';
export const FETCH_COMMUNITY_DATA_FAILURE = 'FETCH_COMMUNITY_DATA_FAILURE';

export const FETCH_ORDER_DATA_REQUEST = 'FETCH_OREDR_DATA_REQUEST';
export const FETCH_ORDER_DATA_SUCCESS = 'FETCH_ORDER_DATA_SUCCESS';
export const FETCH_ORDER_DATA_FAILURE = 'FETCH_ORDER_DATA_FAILURE';
export const RESET_ORDER_DATA = 'RESET_USER_DATA';

export const FETCH_ADMIN_DATA_REQUEST = 'FETCH_ADMIN_DATA_REQUEST';
export const FETCH_ADMIN_DATA_SUCCESS = 'FETCH_ADMIN_DATA_SUCCESS';
export const FETCH_ADMIN_DATA_FAILURE = 'FETCH_ADMIN_DATA_FAILURE';


export const SET_ORDER = 'SET_ORDER';


